package sv.edu.udb.entites;
// Generated 11-10-2020 10:37:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Areas generated by hbm2java
 */
public class Areas  implements java.io.Serializable {


     private int idArea;
     private Clinica clinica;
     private String nombre;
     private Set<Medicos> medicoses = new HashSet<Medicos>(0);

    public Areas() {
    }

	
    public Areas(int idArea, Clinica clinica, String nombre) {
        this.idArea = idArea;
        this.clinica = clinica;
        this.nombre = nombre;
    }
    public Areas(int idArea, Clinica clinica, String nombre, Set<Medicos> medicoses) {
       this.idArea = idArea;
       this.clinica = clinica;
       this.nombre = nombre;
       this.medicoses = medicoses;
    }
   
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }
    public Clinica getClinica() {
        return this.clinica;
    }
    
    public void setClinica(Clinica clinica) {
        this.clinica = clinica;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Medicos> getMedicoses() {
        return this.medicoses;
    }
    
    public void setMedicoses(Set<Medicos> medicoses) {
        this.medicoses = medicoses;
    }




}


