package sv.edu.udb.entites;
// Generated 10-30-2020 09:21:46 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Citas generated by hbm2java
 */
public class Citas  implements java.io.Serializable {


     private int idCita;
     private Medicos medicos;
     private Paciente paciente;
     private Date fecha;
     private String hora;
     private Set<Examenes> exameneses = new HashSet<Examenes>(0);
     private Set<Recetas> recetases = new HashSet<Recetas>(0);

    public Citas() {
    }

	
    public Citas(int idCita, Medicos medicos, Paciente paciente, Date fecha, String hora) {
        this.idCita = idCita;
        this.medicos = medicos;
        this.paciente = paciente;
        this.fecha = fecha;
        this.hora = hora;
    }
    public Citas(int idCita, Medicos medicos, Paciente paciente, Date fecha, String hora, Set<Examenes> exameneses, Set<Recetas> recetases) {
       this.idCita = idCita;
       this.medicos = medicos;
       this.paciente = paciente;
       this.fecha = fecha;
       this.hora = hora;
       this.exameneses = exameneses;
       this.recetases = recetases;
    }
   
    public int getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(int idCita) {
        this.idCita = idCita;
    }
    public Medicos getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Medicos medicos) {
        this.medicos = medicos;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public Set<Examenes> getExameneses() {
        return this.exameneses;
    }
    
    public void setExameneses(Set<Examenes> exameneses) {
        this.exameneses = exameneses;
    }
    public Set<Recetas> getRecetases() {
        return this.recetases;
    }
    
    public void setRecetases(Set<Recetas> recetases) {
        this.recetases = recetases;
    }




}


