package sv.edu.udb.entites;
// Generated 09-17-2020 11:02:11 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Citas generated by hbm2java
 */
public class Citas  implements java.io.Serializable {


     private int idCita;
     private Medicos medicos;
     private Paciente paciente;
     private Date fecha;
     private String hora;
     private String examen;
     private String tipExamen;

    public Citas() {
    }

    public Citas(int idCita, Medicos medicos, Paciente paciente, Date fecha, String hora, String examen, String tipExamen) {
       this.idCita = idCita;
       this.medicos = medicos;
       this.paciente = paciente;
       this.fecha = fecha;
       this.hora = hora;
       this.examen = examen;
       this.tipExamen = tipExamen;
    }
   
    public int getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(int idCita) {
        this.idCita = idCita;
    }
    public Medicos getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Medicos medicos) {
        this.medicos = medicos;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public String getExamen() {
        return this.examen;
    }
    
    public void setExamen(String examen) {
        this.examen = examen;
    }
    public String getTipExamen() {
        return this.tipExamen;
    }
    
    public void setTipExamen(String tipExamen) {
        this.tipExamen = tipExamen;
    }




}


