package sv.edu.udb.entites;
// Generated 09-17-2020 11:02:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clinica generated by hbm2java
 */
public class Clinica  implements java.io.Serializable {


     private int idClinic;
     private String nombre;
     private String direccion;
     private String telefono;
     private Set<Areas> areases = new HashSet<Areas>(0);

    public Clinica() {
    }

	
    public Clinica(int idClinic, String nombre, String direccion, String telefono) {
        this.idClinic = idClinic;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Clinica(int idClinic, String nombre, String direccion, String telefono, Set<Areas> areases) {
       this.idClinic = idClinic;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.areases = areases;
    }
   
    public int getIdClinic() {
        return this.idClinic;
    }
    
    public void setIdClinic(int idClinic) {
        this.idClinic = idClinic;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Areas> getAreases() {
        return this.areases;
    }
    
    public void setAreases(Set<Areas> areases) {
        this.areases = areases;
    }




}


