package sv.edu.udb.entites;
// Generated 10-30-2020 09:21:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clinica generated by hbm2java
 */
public class Clinica  implements java.io.Serializable {


     private int idClinic;
     private String nombre;
     private String direccion;
     private String telefono;
     private Set<Areas> areases = new HashSet<Areas>(0);
     private Set<Farmacia> farmacias = new HashSet<Farmacia>(0);
     private Set<Laboratorio> laboratorios = new HashSet<Laboratorio>(0);

    public Clinica() {
    }

	
    public Clinica(int idClinic, String nombre, String direccion, String telefono) {
        this.idClinic = idClinic;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Clinica(int idClinic, String nombre, String direccion, String telefono, Set<Areas> areases, Set<Farmacia> farmacias, Set<Laboratorio> laboratorios) {
       this.idClinic = idClinic;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.areases = areases;
       this.farmacias = farmacias;
       this.laboratorios = laboratorios;
    }
   
    public int getIdClinic() {
        return this.idClinic;
    }
    
    public void setIdClinic(int idClinic) {
        this.idClinic = idClinic;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Areas> getAreases() {
        return this.areases;
    }
    
    public void setAreases(Set<Areas> areases) {
        this.areases = areases;
    }
    public Set<Farmacia> getFarmacias() {
        return this.farmacias;
    }
    
    public void setFarmacias(Set<Farmacia> farmacias) {
        this.farmacias = farmacias;
    }
    public Set<Laboratorio> getLaboratorios() {
        return this.laboratorios;
    }
    
    public void setLaboratorios(Set<Laboratorio> laboratorios) {
        this.laboratorios = laboratorios;
    }




}


