package sv.edu.udb.entites;
// Generated 11-10-2020 10:37:52 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Examenes generated by hbm2java
 */
public class Examenes  implements java.io.Serializable {


     private String idExam;
     private Citas citas;
     private Laboratorio laboratorio;
     private Tipoexamenes tipoexamenes;
     private String descripcion;
     private Date fechaRealizado;

    public Examenes() {
    }

    public Examenes(String idExam, Citas citas, Laboratorio laboratorio, Tipoexamenes tipoexamenes, String descripcion, Date fechaRealizado) {
       this.idExam = idExam;
       this.citas = citas;
       this.laboratorio = laboratorio;
       this.tipoexamenes = tipoexamenes;
       this.descripcion = descripcion;
       this.fechaRealizado = fechaRealizado;
    }
   
    public String getIdExam() {
        return this.idExam;
    }
    
    public void setIdExam(String idExam) {
        this.idExam = idExam;
    }
    public Citas getCitas() {
        return this.citas;
    }
    
    public void setCitas(Citas citas) {
        this.citas = citas;
    }
    public Laboratorio getLaboratorio() {
        return this.laboratorio;
    }
    
    public void setLaboratorio(Laboratorio laboratorio) {
        this.laboratorio = laboratorio;
    }
    public Tipoexamenes getTipoexamenes() {
        return this.tipoexamenes;
    }
    
    public void setTipoexamenes(Tipoexamenes tipoexamenes) {
        this.tipoexamenes = tipoexamenes;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaRealizado() {
        return this.fechaRealizado;
    }
    
    public void setFechaRealizado(Date fechaRealizado) {
        this.fechaRealizado = fechaRealizado;
    }




}


