package sv.edu.udb.entites;
// Generated 09-17-2020 11:02:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Expediente generated by hbm2java
 */
public class Expediente  implements java.io.Serializable {


     private String idExpe;
     private Paciente paciente;
     private Set<Consulta> consultas = new HashSet<Consulta>(0);

    public Expediente() {
    }

	
    public Expediente(String idExpe, Paciente paciente) {
        this.idExpe = idExpe;
        this.paciente = paciente;
    }
    public Expediente(String idExpe, Paciente paciente, Set<Consulta> consultas) {
       this.idExpe = idExpe;
       this.paciente = paciente;
       this.consultas = consultas;
    }
   
    public String getIdExpe() {
        return this.idExpe;
    }
    
    public void setIdExpe(String idExpe) {
        this.idExpe = idExpe;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Set<Consulta> getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set<Consulta> consultas) {
        this.consultas = consultas;
    }




}


