package sv.edu.udb.entites;
// Generated 10-30-2020 09:21:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Farmacia generated by hbm2java
 */
public class Farmacia  implements java.io.Serializable {


     private int idFarma;
     private Clinica clinica;
     private String horaA;
     private String horaC;
     private Set<Medicamentos> medicamentoses = new HashSet<Medicamentos>(0);

    public Farmacia() {
    }

	
    public Farmacia(int idFarma, Clinica clinica, String horaA, String horaC) {
        this.idFarma = idFarma;
        this.clinica = clinica;
        this.horaA = horaA;
        this.horaC = horaC;
    }
    public Farmacia(int idFarma, Clinica clinica, String horaA, String horaC, Set<Medicamentos> medicamentoses) {
       this.idFarma = idFarma;
       this.clinica = clinica;
       this.horaA = horaA;
       this.horaC = horaC;
       this.medicamentoses = medicamentoses;
    }
   
    public int getIdFarma() {
        return this.idFarma;
    }
    
    public void setIdFarma(int idFarma) {
        this.idFarma = idFarma;
    }
    public Clinica getClinica() {
        return this.clinica;
    }
    
    public void setClinica(Clinica clinica) {
        this.clinica = clinica;
    }
    public String getHoraA() {
        return this.horaA;
    }
    
    public void setHoraA(String horaA) {
        this.horaA = horaA;
    }
    public String getHoraC() {
        return this.horaC;
    }
    
    public void setHoraC(String horaC) {
        this.horaC = horaC;
    }
    public Set<Medicamentos> getMedicamentoses() {
        return this.medicamentoses;
    }
    
    public void setMedicamentoses(Set<Medicamentos> medicamentoses) {
        this.medicamentoses = medicamentoses;
    }




}


