package sv.edu.udb.entites;
// Generated 16-sep-2020 19:45:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Labmedicinas generated by hbm2java
 */
public class Labmedicinas  implements java.io.Serializable {


     private int idLabMed;
     private String nombre;
     private String contacto;
     private Set<Medicamentos> medicamentoses = new HashSet<Medicamentos>(0);

    public Labmedicinas() {
    }

	
    public Labmedicinas(int idLabMed, String nombre, String contacto) {
        this.idLabMed = idLabMed;
        this.nombre = nombre;
        this.contacto = contacto;
    }
    public Labmedicinas(int idLabMed, String nombre, String contacto, Set<Medicamentos> medicamentoses) {
       this.idLabMed = idLabMed;
       this.nombre = nombre;
       this.contacto = contacto;
       this.medicamentoses = medicamentoses;
    }
   
    public int getIdLabMed() {
        return this.idLabMed;
    }
    
    public void setIdLabMed(int idLabMed) {
        this.idLabMed = idLabMed;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public Set<Medicamentos> getMedicamentoses() {
        return this.medicamentoses;
    }
    
    public void setMedicamentoses(Set<Medicamentos> medicamentoses) {
        this.medicamentoses = medicamentoses;
    }




}


