package sv.edu.udb.entites;
// Generated 10-30-2020 09:21:46 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Laboratorio generated by hbm2java
 */
public class Laboratorio  implements java.io.Serializable {


     private int idLab;
     private Clinica clinica;
     private String horaA;
     private String horaC;
     private Set<Examenes> exameneses = new HashSet<Examenes>(0);

    public Laboratorio() {
    }

	
    public Laboratorio(int idLab, Clinica clinica, String horaA, String horaC) {
        this.idLab = idLab;
        this.clinica = clinica;
        this.horaA = horaA;
        this.horaC = horaC;
    }
    public Laboratorio(int idLab, Clinica clinica, String horaA, String horaC, Set<Examenes> exameneses) {
       this.idLab = idLab;
       this.clinica = clinica;
       this.horaA = horaA;
       this.horaC = horaC;
       this.exameneses = exameneses;
    }
   
    public int getIdLab() {
        return this.idLab;
    }
    
    public void setIdLab(int idLab) {
        this.idLab = idLab;
    }
    public Clinica getClinica() {
        return this.clinica;
    }
    
    public void setClinica(Clinica clinica) {
        this.clinica = clinica;
    }
    public String getHoraA() {
        return this.horaA;
    }
    
    public void setHoraA(String horaA) {
        this.horaA = horaA;
    }
    public String getHoraC() {
        return this.horaC;
    }
    
    public void setHoraC(String horaC) {
        this.horaC = horaC;
    }
    public Set<Examenes> getExameneses() {
        return this.exameneses;
    }
    
    public void setExameneses(Set<Examenes> exameneses) {
        this.exameneses = exameneses;
    }




}


