package sv.edu.udb.entites;
// Generated 09-17-2020 11:02:11 PM by Hibernate Tools 4.3.1



/**
 * Medicamentos generated by hbm2java
 */
public class Medicamentos  implements java.io.Serializable {


     private String idMedicamento;
     private Labmedicinas labmedicinas;
     private String nombre;
     private String descripcion;
     private String mg;
     private int cantidadDisp;

    public Medicamentos() {
    }

    public Medicamentos(String idMedicamento, Labmedicinas labmedicinas, String nombre, String descripcion, String mg, int cantidadDisp) {
       this.idMedicamento = idMedicamento;
       this.labmedicinas = labmedicinas;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.mg = mg;
       this.cantidadDisp = cantidadDisp;
    }
   
    public String getIdMedicamento() {
        return this.idMedicamento;
    }
    
    public void setIdMedicamento(String idMedicamento) {
        this.idMedicamento = idMedicamento;
    }
    public Labmedicinas getLabmedicinas() {
        return this.labmedicinas;
    }
    
    public void setLabmedicinas(Labmedicinas labmedicinas) {
        this.labmedicinas = labmedicinas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getMg() {
        return this.mg;
    }
    
    public void setMg(String mg) {
        this.mg = mg;
    }
    public int getCantidadDisp() {
        return this.cantidadDisp;
    }
    
    public void setCantidadDisp(int cantidadDisp) {
        this.cantidadDisp = cantidadDisp;
    }




}


