package sv.edu.udb.entites;
// Generated 09-20-2020 11:06:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Recetas generated by hbm2java
 */
public class Recetas  implements java.io.Serializable {


     private int idReceta;
     private Medicos medicos;
     private Paciente paciente;
     private Set<Medicina> medicinas = new HashSet<Medicina>(0);

    public Recetas() {
    }

	
    public Recetas(int idReceta, Medicos medicos, Paciente paciente) {
        this.idReceta = idReceta;
        this.medicos = medicos;
        this.paciente = paciente;
    }
    public Recetas(int idReceta, Medicos medicos, Paciente paciente, Set<Medicina> medicinas) {
       this.idReceta = idReceta;
       this.medicos = medicos;
       this.paciente = paciente;
       this.medicinas = medicinas;
    }
   
    public int getIdReceta() {
        return this.idReceta;
    }
    
    public void setIdReceta(int idReceta) {
        this.idReceta = idReceta;
    }
    public Medicos getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Medicos medicos) {
        this.medicos = medicos;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Set<Medicina> getMedicinas() {
        return this.medicinas;
    }
    
    public void setMedicinas(Set<Medicina> medicinas) {
        this.medicinas = medicinas;
    }




}


