package sv.edu.udb.entites;
// Generated 11-10-2020 10:37:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Recetas generated by hbm2java
 */
public class Recetas  implements java.io.Serializable {


     private int idReceta;
     private Citas citas;
     private Set<Medicina> medicinas = new HashSet<Medicina>(0);

    public Recetas() {
    }

	
    public Recetas(int idReceta, Citas citas) {
        this.idReceta = idReceta;
        this.citas = citas;
    }
    public Recetas(int idReceta, Citas citas, Set<Medicina> medicinas) {
       this.idReceta = idReceta;
       this.citas = citas;
       this.medicinas = medicinas;
    }
   
    public int getIdReceta() {
        return this.idReceta;
    }
    
    public void setIdReceta(int idReceta) {
        this.idReceta = idReceta;
    }
    public Citas getCitas() {
        return this.citas;
    }
    
    public void setCitas(Citas citas) {
        this.citas = citas;
    }
    public Set<Medicina> getMedicinas() {
        return this.medicinas;
    }
    
    public void setMedicinas(Set<Medicina> medicinas) {
        this.medicinas = medicinas;
    }




}


