package sv.edu.udb.entites;
// Generated 11-10-2020 10:37:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private int idTipo;
     private String tipo;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Tipousuario() {
    }

	
    public Tipousuario(int idTipo, String tipo) {
        this.idTipo = idTipo;
        this.tipo = tipo;
    }
    public Tipousuario(int idTipo, String tipo, Set<Usuario> usuarios) {
       this.idTipo = idTipo;
       this.tipo = tipo;
       this.usuarios = usuarios;
    }
   
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


