package sv.edu.udb.entites;
// Generated 16-sep-2020 19:45:19 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String usuario;
     private String nombre;
     private String apellido;
     private String contrasena;
     private String verificar;

    public Usuario() {
    }

    public Usuario(String usuario, String nombre, String apellido, String contrasena, String verificar) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.contrasena = contrasena;
       this.verificar = verificar;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getVerificar() {
        return this.verificar;
    }
    
    public void setVerificar(String verificar) {
        this.verificar = verificar;
    }




}


