package sv.edu.udb.entites;
// Generated 09-20-2020 11:06:04 AM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String usuario;
     private Tipousuario tipousuario;
     private String contrasena;
     private String correo;
     private String verificar;

    public Usuario() {
    }

    public Usuario(String usuario, Tipousuario tipousuario, String contrasena, String correo, String verificar) {
       this.usuario = usuario;
       this.tipousuario = tipousuario;
       this.contrasena = contrasena;
       this.correo = correo;
       this.verificar = verificar;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getVerificar() {
        return this.verificar;
    }
    
    public void setVerificar(String verificar) {
        this.verificar = verificar;
    }




}


